# Generated by Django 3.2.8 on 2021-10-28 15:37

from django.db import migrations


def move_on(apps, schema_editor):
    print("this is hopefully a no-op placeholder; when I have more time I'll find a more-elegant method of resequencing migration files' logic")


class Migration(migrations.Migration):
    dependencies = [
        ('fourchar', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(move_on),
    ]
