# Generated by Django 3.2.8 on 2021-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourchar', '0002_auto_20211028_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='chengyu',
            name='chengyu_text',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chengyu',
            name='chengyu_translation',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chengyu',
            name='demo_sentence_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chengyu',
            name='demo_sentence_pn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chengyu',
            name='demo_sentence_zh',
            field=models.TextField(),
        ),
    ]
