# Generated by Django 3.2.8 on 2021-10-28 16:20

from django.db import migrations


def seed_chengyu(apps, schema_editor):
    Chengyu = apps.get_model('fourchar', 'Chengyu')
    f = open("chengyu.10m.txt", "r")
    lines = f.readlines()

    for line in lines:
        print(line, end="")
        Chengyu.objects.create(chengyu_text=line.replace("\n", ""))


def delete_seed_data(apps, schema_editor):
    Chengyu = apps.get_model('fourchar', 'Chengyu')
    for chengyu in Chengyu.objects.all():
        chengyu.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fourchar', '0003_auto_20211028_1109'),
    ]

    operations = [
        migrations.RunPython(seed_chengyu, delete_seed_data),
    ]
