# Generated by Django 3.2.8 on 2021-10-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourchar', '0004_auto_20211028_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chengyu',
            name='z_rarity',
            field=models.IntegerField(choices=[(1, 'Very Common'), (2, 'Common'), (3, 'Uncommon'), (4, 'Rare'), (5, 'Very Rare')], default=3),
        ),
    ]
